runtime: nodejs20

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
  - url: /(.*\.(gif|png|jpg|ico|txt|svg|woff|woff2|ttf|eot|json))$
    static_files: build/\1
    upload: build/(.*\.(gif|png|jpg|ico|txt|svg|woff|woff2|ttf|eot|json))$
  - url: /.*
    script: auto
